USE `sp_api`;
INSERT INTO `municipios` VALUES (1, 'Arujá');
INSERT INTO `municipios` VALUES (2, 'Barueri');
INSERT INTO `municipios` VALUES (3, 'Biritiba-Mirim');
INSERT INTO `municipios` VALUES (4, 'Caieiras');
INSERT INTO `municipios` VALUES (5, 'Cajamar');
INSERT INTO `municipios` VALUES (6, 'Carapicuíba');
INSERT INTO `municipios` VALUES (7, 'Cotia');
INSERT INTO `municipios` VALUES (8, 'Diadema');
INSERT INTO `municipios` VALUES (9, 'Embu das Artes');
INSERT INTO `municipios` VALUES (10, 'Embu-Guaçu');
INSERT INTO `municipios` VALUES (11, 'Ferraz de Vasconcelos');
INSERT INTO `municipios` VALUES (12, 'Francisco Morato');
INSERT INTO `municipios` VALUES (13, 'Franco da Rocha');
INSERT INTO `municipios` VALUES (14, 'Guararema');
INSERT INTO `municipios` VALUES (15, 'Guarulhos');
INSERT INTO `municipios` VALUES (16, 'Itapecerica da Serra');
INSERT INTO `municipios` VALUES (17, 'Itapevi');
INSERT INTO `municipios` VALUES (18, 'Itaquaquecetuba');
INSERT INTO `municipios` VALUES (19, 'Jandira');
INSERT INTO `municipios` VALUES (20, 'Juquitiba');
INSERT INTO `municipios` VALUES (21, 'Mairiporã');
INSERT INTO `municipios` VALUES (22, 'Mauá');
INSERT INTO `municipios` VALUES (23, 'Mogi das Cruzes');
INSERT INTO `municipios` VALUES (24, 'Osasco');
INSERT INTO `municipios` VALUES (25, 'Pirapora do Bom Jesus');
INSERT INTO `municipios` VALUES (26, 'Poá');
INSERT INTO `municipios` VALUES (27, 'Ribeirão Pires');
INSERT INTO `municipios` VALUES (28, 'Rio Grande da Serra');
INSERT INTO `municipios` VALUES (29, 'Salesópolis');
INSERT INTO `municipios` VALUES (30, 'Santa Isabel');
INSERT INTO `municipios` VALUES (31, 'Santana de Parnaíba');
INSERT INTO `municipios` VALUES (32, 'Santo André');
INSERT INTO `municipios` VALUES (33, 'São Bernardo do Campo');
INSERT INTO `municipios` VALUES (34, 'São Caetano do Sul');
INSERT INTO `municipios` VALUES (35, 'São Lourenço da Serra');
INSERT INTO `municipios` VALUES (36, 'São Paulo');
INSERT INTO `municipios` VALUES (37, 'Suzano');
INSERT INTO `municipios` VALUES (38, 'Taboão da Serra');
INSERT INTO `municipios` VALUES (39, 'Vargem Grande Paulista');
INSERT INTO `distritos` VALUES (1, 'Água Rasa');
INSERT INTO `distritos` VALUES (2, 'Alto de Pinheiros');
INSERT INTO `distritos` VALUES (3, 'Anhanguera');
INSERT INTO `distritos` VALUES (4, 'Aricanduva');
INSERT INTO `distritos` VALUES (5, 'Artur Alvim');
INSERT INTO `distritos` VALUES (6, 'Barra Funda');
INSERT INTO `distritos` VALUES (7, 'Bela Vista');
INSERT INTO `distritos` VALUES (8, 'Belém');
INSERT INTO `distritos` VALUES (9, 'Bom Retiro');
INSERT INTO `distritos` VALUES (10, 'Brás');
INSERT INTO `distritos` VALUES (11, 'Brasilândia');
INSERT INTO `distritos` VALUES (12, 'Butantã');
INSERT INTO `distritos` VALUES (13, 'Cachoeirinha');
INSERT INTO `distritos` VALUES (14, 'Cambuci');
INSERT INTO `distritos` VALUES (15, 'Campo Belo');
INSERT INTO `distritos` VALUES (16, 'Campo Grande');
INSERT INTO `distritos` VALUES (17, 'Campo Limpo');
INSERT INTO `distritos` VALUES (18, 'Cangaíba');
INSERT INTO `distritos` VALUES (19, 'Capão Redondo');
INSERT INTO `distritos` VALUES (20, 'Carrão');
INSERT INTO `distritos` VALUES (21, 'Casa Verde');
INSERT INTO `distritos` VALUES (22, 'Cidade Ademar');
INSERT INTO `distritos` VALUES (23, 'Cidade Dutra');
INSERT INTO `distritos` VALUES (24, 'Cidade Líder');
INSERT INTO `distritos` VALUES (25, 'Cidade Tiradentes');
INSERT INTO `distritos` VALUES (26, 'Consolação');
INSERT INTO `distritos` VALUES (27, 'Cursino');
INSERT INTO `distritos` VALUES (28, 'Ermelino Matarazzo');
INSERT INTO `distritos` VALUES (29, 'Freguesia do Ó');
INSERT INTO `distritos` VALUES (30, 'Grajaú');
INSERT INTO `distritos` VALUES (31, 'Guaianases');
INSERT INTO `distritos` VALUES (32, 'Iguatemi');
INSERT INTO `distritos` VALUES (33, 'Ipiranga');
INSERT INTO `distritos` VALUES (34, 'Itaim Bibi');
INSERT INTO `distritos` VALUES (35, 'Itaim Paulista');
INSERT INTO `distritos` VALUES (36, 'Itaquera');
INSERT INTO `distritos` VALUES (37, 'Jabaquara');
INSERT INTO `distritos` VALUES (38, 'Jaçanã');
INSERT INTO `distritos` VALUES (39, 'Jaguara');
INSERT INTO `distritos` VALUES (40, 'Jaguaré');
INSERT INTO `distritos` VALUES (41, 'Jaraguá');
INSERT INTO `distritos` VALUES (42, 'Jardim Ângela');
INSERT INTO `distritos` VALUES (43, 'Jardim Helena');
INSERT INTO `distritos` VALUES (44, 'Jardim Paulista');
INSERT INTO `distritos` VALUES (45, 'Jardim São Luís');
INSERT INTO `distritos` VALUES (46, 'José Bonifácio');
INSERT INTO `distritos` VALUES (47, 'Lajeado');
INSERT INTO `distritos` VALUES (48, 'Lapa');
INSERT INTO `distritos` VALUES (49, 'Liberdade');
INSERT INTO `distritos` VALUES (50, 'Limão');
INSERT INTO `distritos` VALUES (51, 'Mandaqui');
INSERT INTO `distritos` VALUES (52, 'Marsilac');
INSERT INTO `distritos` VALUES (53, 'Moema');
INSERT INTO `distritos` VALUES (54, 'Moóca');
INSERT INTO `distritos` VALUES (55, 'Morumbi');
INSERT INTO `distritos` VALUES (56, 'Parelheiros');
INSERT INTO `distritos` VALUES (57, 'Pari');
INSERT INTO `distritos` VALUES (58, 'Parque do Carmo');
INSERT INTO `distritos` VALUES (59, 'Pedreira');
INSERT INTO `distritos` VALUES (60, 'Penha');
INSERT INTO `distritos` VALUES (61, 'Perdizes');
INSERT INTO `distritos` VALUES (62, 'Perus');
INSERT INTO `distritos` VALUES (63, 'Pinheiros');
INSERT INTO `distritos` VALUES (64, 'Pirituba');
INSERT INTO `distritos` VALUES (65, 'Ponte Rasa');
INSERT INTO `distritos` VALUES (66, 'Raposo Tavares');
INSERT INTO `distritos` VALUES (67, 'República');
INSERT INTO `distritos` VALUES (68, 'Rio Pequeno');
INSERT INTO `distritos` VALUES (69, 'Sacomã');
INSERT INTO `distritos` VALUES (70, 'Santa Cecília');
INSERT INTO `distritos` VALUES (71, 'Santana');
INSERT INTO `distritos` VALUES (72, 'Santo Amaro');
INSERT INTO `distritos` VALUES (73, 'São Domingos');
INSERT INTO `distritos` VALUES (74, 'São Lucas');
INSERT INTO `distritos` VALUES (75, 'São Mateus');
INSERT INTO `distritos` VALUES (76, 'São Miguel Paulista');
INSERT INTO `distritos` VALUES (77, 'São Rafael');
INSERT INTO `distritos` VALUES (78, 'Sapopemba');
INSERT INTO `distritos` VALUES (79, 'Saúde');
INSERT INTO `distritos` VALUES (80, 'Sé');
INSERT INTO `distritos` VALUES (81, 'Socorro');
INSERT INTO `distritos` VALUES (82, 'Tatuapé');
INSERT INTO `distritos` VALUES (83, 'Tremembé');
INSERT INTO `distritos` VALUES (84, 'Tucuruvi');
INSERT INTO `distritos` VALUES (85, 'Vila Andrade');
INSERT INTO `distritos` VALUES (86, 'Vila Curuçá');
INSERT INTO `distritos` VALUES (87, 'Vila Formosa');
INSERT INTO `distritos` VALUES (88, 'Vila Guilherme');
INSERT INTO `distritos` VALUES (89, 'Vila Jacuí');
INSERT INTO `distritos` VALUES (90, 'Vila Leopoldina');
INSERT INTO `distritos` VALUES (91, 'Vila Maria');
INSERT INTO `distritos` VALUES (92, 'Vila Mariana');
INSERT INTO `distritos` VALUES (93, 'Vila Matilde');
INSERT INTO `distritos` VALUES (94, 'Vila Medeiros');
INSERT INTO `distritos` VALUES (95, 'Vila Prudente');
INSERT INTO `distritos` VALUES (96, 'Vila Sônia');
INSERT INTO `distritos` VALUES (97, 'Caieiras');
INSERT INTO `distritos` VALUES (98, 'Cajamar');
INSERT INTO `distritos` VALUES (99, 'Francisco Morato');
INSERT INTO `distritos` VALUES (100, 'Franco da Rocha');
INSERT INTO `distritos` VALUES (101, 'Mairiporã');
INSERT INTO `distritos` VALUES (102, 'Arujá');
INSERT INTO `distritos` VALUES (103, 'Guarulhos');
INSERT INTO `distritos` VALUES (104, 'Santa Isabel');
INSERT INTO `distritos` VALUES (105, 'Biritiba-Mirim');
INSERT INTO `distritos` VALUES (106, 'Ferraz de Vasconcelos');
INSERT INTO `distritos` VALUES (107, 'Guararema');
INSERT INTO `distritos` VALUES (108, 'Itaquaquecetuba');
INSERT INTO `distritos` VALUES (109, 'Mogi das Cruzes');
INSERT INTO `distritos` VALUES (110, 'Poá');
INSERT INTO `distritos` VALUES (111, 'Salesópolis');
INSERT INTO `distritos` VALUES (112, 'Suzano');
INSERT INTO `distritos` VALUES (113, 'Mauá');
INSERT INTO `distritos` VALUES (114, 'Ribeirão Pires');
INSERT INTO `distritos` VALUES (115, 'Rio Grande da Serra');
INSERT INTO `distritos` VALUES (116, 'Santo André');
INSERT INTO `distritos` VALUES (117, 'São Caetano do Sul');
INSERT INTO `distritos` VALUES (118, 'Diadema');
INSERT INTO `distritos` VALUES (119, 'São Bernardo do Campo');
INSERT INTO `distritos` VALUES (120, 'Embu das Artes');
INSERT INTO `distritos` VALUES (121, 'Embu-Guaçu');
INSERT INTO `distritos` VALUES (122, 'Itapecerica da Serra');
INSERT INTO `distritos` VALUES (123, 'Juquitiba');
INSERT INTO `distritos` VALUES (124, 'São Lourenço da Serra');
INSERT INTO `distritos` VALUES (125, 'Taboão da Serra');
INSERT INTO `distritos` VALUES (126, 'Cotia');
INSERT INTO `distritos` VALUES (127, 'Vargem Grande Paulista');
INSERT INTO `distritos` VALUES (128, 'Barueri');
INSERT INTO `distritos` VALUES (129, 'Carapicuíba');
INSERT INTO `distritos` VALUES (130, 'Itapevi');
INSERT INTO `distritos` VALUES (131, 'Jandira');
INSERT INTO `distritos` VALUES (132, 'Osasco');
INSERT INTO `distritos` VALUES (133, 'Pirapora do Bom Jesus');
INSERT INTO `distritos` VALUES (134, 'Santana de Parnaíba');
INSERT INTO `zonas` VALUES (1, 7, 36);
INSERT INTO `zonas` VALUES (1, 9, 36);
INSERT INTO `zonas` VALUES (1, 10, 36);
INSERT INTO `zonas` VALUES (1, 14, 36);
INSERT INTO `zonas` VALUES (1, 26, 36);
INSERT INTO `zonas` VALUES (1, 49, 36);
INSERT INTO `zonas` VALUES (1, 57, 36);
INSERT INTO `zonas` VALUES (1, 67, 36);
INSERT INTO `zonas` VALUES (1, 70, 36);
INSERT INTO `zonas` VALUES (1, 80, 36);
INSERT INTO `zonas` VALUES (2, 3, 36);
INSERT INTO `zonas` VALUES (2, 39, 36);
INSERT INTO `zonas` VALUES (2, 41, 36);
INSERT INTO `zonas` VALUES (2, 62, 36);
INSERT INTO `zonas` VALUES (2, 64, 36);
INSERT INTO `zonas` VALUES (2, 73, 36);
INSERT INTO `zonas` VALUES (3, 11, 36);
INSERT INTO `zonas` VALUES (3, 13, 36);
INSERT INTO `zonas` VALUES (3, 21, 36);
INSERT INTO `zonas` VALUES (3, 29, 36);
INSERT INTO `zonas` VALUES (3, 50, 36);
INSERT INTO `zonas` VALUES (4, 38, 36);
INSERT INTO `zonas` VALUES (4, 51, 36);
INSERT INTO `zonas` VALUES (4, 71, 36);
INSERT INTO `zonas` VALUES (4, 83, 36);
INSERT INTO `zonas` VALUES (4, 84, 36);
INSERT INTO `zonas` VALUES (4, 88, 36);
INSERT INTO `zonas` VALUES (4, 91, 36);
INSERT INTO `zonas` VALUES (4, 94, 36);
INSERT INTO `zonas` VALUES (5, 1, 36);
INSERT INTO `zonas` VALUES (5, 8, 36);
INSERT INTO `zonas` VALUES (5, 54, 36);
INSERT INTO `zonas` VALUES (6, 74, 36);
INSERT INTO `zonas` VALUES (6, 78, 36);
INSERT INTO `zonas` VALUES (6, 95, 36);
INSERT INTO `zonas` VALUES (7, 4, 36);
INSERT INTO `zonas` VALUES (7, 20, 36);
INSERT INTO `zonas` VALUES (7, 82, 36);
INSERT INTO `zonas` VALUES (7, 87, 36);
INSERT INTO `zonas` VALUES (8, 5, 36);
INSERT INTO `zonas` VALUES (8, 24, 36);
INSERT INTO `zonas` VALUES (8, 93, 36);
INSERT INTO `zonas` VALUES (9, 18, 36);
INSERT INTO `zonas` VALUES (9, 28, 36);
INSERT INTO `zonas` VALUES (9, 60, 36);
INSERT INTO `zonas` VALUES (9, 65, 36);
INSERT INTO `zonas` VALUES (10, 35, 36);
INSERT INTO `zonas` VALUES (10, 43, 36);
INSERT INTO `zonas` VALUES (10, 76, 36);
INSERT INTO `zonas` VALUES (10, 86, 36);
INSERT INTO `zonas` VALUES (10, 89, 36);
INSERT INTO `zonas` VALUES (11, 36, 36);
INSERT INTO `zonas` VALUES (11, 46, 36);
INSERT INTO `zonas` VALUES (11, 58, 36);
INSERT INTO `zonas` VALUES (12, 32, 36);
INSERT INTO `zonas` VALUES (12, 75, 36);
INSERT INTO `zonas` VALUES (12, 77, 36);
INSERT INTO `zonas` VALUES (13, 25, 36);
INSERT INTO `zonas` VALUES (13, 31, 36);
INSERT INTO `zonas` VALUES (13, 47, 36);
INSERT INTO `zonas` VALUES (14, 44, 36);
INSERT INTO `zonas` VALUES (14, 63, 36);
INSERT INTO `zonas` VALUES (15, 15, 36);
INSERT INTO `zonas` VALUES (15, 34, 36);
INSERT INTO `zonas` VALUES (15, 53, 36);
INSERT INTO `zonas` VALUES (16, 79, 36);
INSERT INTO `zonas` VALUES (16, 92, 36);
INSERT INTO `zonas` VALUES (17, 27, 36);
INSERT INTO `zonas` VALUES (17, 33, 36);
INSERT INTO `zonas` VALUES (17, 69, 36);
INSERT INTO `zonas` VALUES (18, 16, 36);
INSERT INTO `zonas` VALUES (18, 22, 36);
INSERT INTO `zonas` VALUES (18, 37, 36);
INSERT INTO `zonas` VALUES (18, 59, 36);
INSERT INTO `zonas` VALUES (18, 72, 36);
INSERT INTO `zonas` VALUES (19, 23, 36);
INSERT INTO `zonas` VALUES (19, 30, 36);
INSERT INTO `zonas` VALUES (19, 52, 36);
INSERT INTO `zonas` VALUES (19, 56, 36);
INSERT INTO `zonas` VALUES (19, 81, 36);
INSERT INTO `zonas` VALUES (20, 19, 36);
INSERT INTO `zonas` VALUES (20, 42, 36);
INSERT INTO `zonas` VALUES (20, 45, 36);
INSERT INTO `zonas` VALUES (21, 17, 36);
INSERT INTO `zonas` VALUES (21, 55, 36);
INSERT INTO `zonas` VALUES (21, 85, 36);
INSERT INTO `zonas` VALUES (21, 96, 36);
INSERT INTO `zonas` VALUES (22, 12, 36);
INSERT INTO `zonas` VALUES (22, 40, 36);
INSERT INTO `zonas` VALUES (22, 66, 36);
INSERT INTO `zonas` VALUES (22, 68, 36);
INSERT INTO `zonas` VALUES (23, 2, 36);
INSERT INTO `zonas` VALUES (23, 6, 36);
INSERT INTO `zonas` VALUES (23, 48, 36);
INSERT INTO `zonas` VALUES (23, 61, 36);
INSERT INTO `zonas` VALUES (23, 90, 36);
INSERT INTO `zonas` VALUES (24, 97, 4);
INSERT INTO `zonas` VALUES (24, 98, 5);
INSERT INTO `zonas` VALUES (24, 99, 12);
INSERT INTO `zonas` VALUES (24, 100, 13);
INSERT INTO `zonas` VALUES (24, 101, 21);
INSERT INTO `zonas` VALUES (25, 102, 1);
INSERT INTO `zonas` VALUES (25, 103, 15);
INSERT INTO `zonas` VALUES (25, 104, 30);
INSERT INTO `zonas` VALUES (26, 105, 3);
INSERT INTO `zonas` VALUES (26, 106, 11);
INSERT INTO `zonas` VALUES (26, 107, 14);
INSERT INTO `zonas` VALUES (26, 108, 18);
INSERT INTO `zonas` VALUES (26, 109, 23);
INSERT INTO `zonas` VALUES (26, 110, 26);
INSERT INTO `zonas` VALUES (26, 111, 29);
INSERT INTO `zonas` VALUES (26, 112, 37);
INSERT INTO `zonas` VALUES (27, 113, 22);
INSERT INTO `zonas` VALUES (27, 114, 27);
INSERT INTO `zonas` VALUES (27, 115, 28);
INSERT INTO `zonas` VALUES (27, 116, 32);
INSERT INTO `zonas` VALUES (27, 117, 34);
INSERT INTO `zonas` VALUES (28, 118, 8);
INSERT INTO `zonas` VALUES (28, 119, 33);
INSERT INTO `zonas` VALUES (29, 120, 9);
INSERT INTO `zonas` VALUES (29, 121, 10);
INSERT INTO `zonas` VALUES (29, 122, 16);
INSERT INTO `zonas` VALUES (29, 123, 20);
INSERT INTO `zonas` VALUES (29, 124, 35);
INSERT INTO `zonas` VALUES (29, 125, 38);
INSERT INTO `zonas` VALUES (30, 126, 7);
INSERT INTO `zonas` VALUES (30, 127, 39);
INSERT INTO `zonas` VALUES (31, 128, 2);
INSERT INTO `zonas` VALUES (31, 129, 6);
INSERT INTO `zonas` VALUES (31, 130, 17);
INSERT INTO `zonas` VALUES (31, 131, 19);
INSERT INTO `zonas` VALUES (31, 132, 24);
INSERT INTO `zonas` VALUES (31, 133, 25);
INSERT INTO `zonas` VALUES (31, 134, 31);
