USE `sp_api`;
INSERT INTO `transportes` VALUES (1, 'Ônibus Município S.Paulo');
INSERT INTO `transportes` VALUES (2, 'Ônibus Outros Municípios');
INSERT INTO `transportes` VALUES (3, 'Ônibus Metropolitano');
INSERT INTO `transportes` VALUES (4, 'Ônibus Fretado');
INSERT INTO `transportes` VALUES (5, 'Escolar');
INSERT INTO `transportes` VALUES (6, 'Dirigindo Automóvel');
INSERT INTO `transportes` VALUES (7, 'Passageiro de Automóvel');
INSERT INTO `transportes` VALUES (8, 'Táxi');
INSERT INTO `transportes` VALUES (9, 'Microônibus/Van Município de S.Paulo');
INSERT INTO `transportes` VALUES (10, 'Microônibus/Van Outros Município');
INSERT INTO `transportes` VALUES (11, 'Microônibus/Van Metropolitano');
INSERT INTO `transportes` VALUES (12, 'Metrô');
INSERT INTO `transportes` VALUES (13, 'Trem');
INSERT INTO `transportes` VALUES (14, 'Moto');
INSERT INTO `transportes` VALUES (15, 'Bicicleta');
INSERT INTO `transportes` VALUES (16, 'A Pé');
INSERT INTO `transportes` VALUES (17, 'Outros');
