CREATE SCHEMA `sp_api` DEFAULT CHARSET=utf8;

CREATE TABLE `regions` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  `region` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
